export const CITIES_LIST = [
  "Ahmedabad", "Ajmer", "Amritsar", "Anand", "Armoor", "Aurangabad", "Bareilly", "Belagavi", "Belgaum", "Bangalore",
  "Bhilai", "Bhilwara", "Bhiwadi", "Bhopal", "Bhubaneswar", "Bilaspur", "Bokaro", "Burdwan", "Chandigarh", "Chennai",
  "Coimbatore", "Cuttack", "Dehradun", "Delhi", "Dhanbad", "Dharwad", "Faridabad", "Gandhinagar", "Gangtok", "Ghaziabad",
  "Goa", "Gorakhpur", "Greater Noida", "Gulbarga", "Guntur", "Gurgaon", "Guwahati", "Gwalior", "Howrah", "Hyderabad",
  "Indore", "Jabalpur", "Jaipur", "Jalandhar", "Jalgaon", "Jammu", "Jamnagar", "Jodhpur", "Jorhat", "Kakinada",
  "Kalyan", "Kanpur", "Khanna", "Cochin", "Kolkata", "Kolhapur", "Kota", "Latur", "Leh", "Liluah",
  "Lucknow", "Ludhiana", "Machillipatnam", "Madurai", "Mangalore", "Manipal", "Meerut", "Mohali", "Moradabad", "Mumbai",
  "Mysuru", "Nadiad", "Nagpur", "Nanded", "Narsipatnam", "Nashik", "Nizamabad", "Noida", "Panchkula", "Panipat",
  "Pathankot", "Patiala", "Patna", "Pondicherry", "Allahabad", "Pune", "Raipur", "Rajkot", "Ranchi", "Rourkela",
  "Salem", "Siliguri", "Sri Ganganagar", "Srinagar", "Surat", "Thane", "Thrissur", "Trivandrum", "Tumakuru"
].sort();

export const CLASSES_LIST = [
  '1st Std', '2nd Std', '3rd Std', '4th Std', '5th Std',
  '6th Std', '7th Std', '8th Std', '9th Std', '10th Std',
  '11th Std', '12th Std'
];

export const CLASS_SUBJECTS_DATA: Record<string, string[]> = {
    '1st Std': [
        "All Subjects (General)",
        "English",
        "Hindi",
        "Maths",
        "EVS",
        "Jolly Phonics",
        "Abacus",
        "Vedic Maths",
        "Computer",
        "Cursive Writing",
        "Storytelling",
        "Art & Craft"
    ],
    '2nd Std': [
        "All Subjects (General)",
        "English",
        "Hindi",
        "Maths",
        "EVS",
        "Jolly Phonics",
        "Abacus",
        "Vedic Maths",
        "Computer",
        "Cursive Writing",
        "Storytelling",
        "Art & Craft"
    ],
    '3rd Std': [
        "All Subjects (General)",
        "English",
        "Hindi",
        "Maths",
        "EVS",
        "Jolly Phonics",
        "Abacus",
        "Vedic Maths",
        "Computer",
        "Cursive Writing",
        "Storytelling",
        "Art & Craft"
    ],
    '4th Std': [
        "All Subjects (General)",
        "English",
        "Hindi",
        "Maths",
        "EVS",
        "Jolly Phonics",
        "Abacus",
        "Vedic Maths",
        "Computer",
        "Cursive Writing",
        "Storytelling",
        "Art & Craft"
    ],
    '5th Std': [
        "All Subjects (General)",
        "English",
        "Hindi",
        "Maths",
        "EVS",
        "Jolly Phonics",
        "Abacus",
        "Vedic Maths",
        "Computer",
        "Cursive Writing",
        "Storytelling",
        "Art & Craft"
    ],
    '6th Std': [
        "Maths",
        "Science (Physics, Chemistry, Biology)",
        "Social Science (SST)",
        "English",
        "Hindi",
        "Sanskrit",
        "French",
        "German",
        "Spanish",
        "Computer/ICT",
        "Robotics"
    ],
    '7th Std': [
        "Maths",
        "Science (Physics, Chemistry, Biology)",
        "Social Science (SST)",
        "English",
        "Hindi",
        "Sanskrit",
        "French",
        "German",
        "Spanish",
        "Computer/ICT",
        "Robotics"
    ],
    '8th Std': [
        "Maths",
        "Science (Physics, Chemistry, Biology)",
        "Social Science (SST)",
        "English",
        "Hindi",
        "Sanskrit",
        "French",
        "German",
        "Spanish",
        "Computer/ICT",
        "Robotics"
    ],
    '9th Std': [
        "Maths",
        "Maths (Standard/Basic)",
        "Science (Physics, Chemistry, Biology)",
        "Physics",
        "Chemistry",
        "Biology",
        "Social Science (SST)",
        "History",
        "Civics",
        "Geography",
        "Economics",
        "English",
        "English (Language & Literature)",
        "Hindi",
        "Hindi (A/B)",
        "Sanskrit",
        "French",
        "German",
        "Spanish",
        "Computer/ICT",
        "Information Technology (IT)",
        "Robotics",
        "Artificial Intelligence (AI)"
    ],
    '10th Std': [
        "Maths (Standard/Basic)",
        "Physics",
        "Chemistry",
        "Biology",
        "History",
        "Civics",
        "Geography",
        "Economics",
        "English (Language & Literature)",
        "Hindi (A/B)",
        "French",
        "German",
        "Information Technology (IT)",
        "Artificial Intelligence (AI)"
    ],
    '11th Std': [
        "Physics",
        "Chemistry",
        "Maths",
        "Biology",
        "Biotechnology",
        "IP",
        "Accounts",
        "Business Studies",
        "Economics",
        "Applied Maths",
        "Entrepreneurship",
        "Psychology",
        "Sociology",
        "Political Science",
        "History",
        "Geography",
        "Home Science",
        "Legal Studies",
        "English Core",
        "English Elective",
        "Physical Education",
        "Fine Arts"
    ],
    '12th Std': [
        "Physics",
        "Chemistry",
        "Maths",
        "Biology",
        "Biotechnology",
        "IP",
        "Accounts",
        "Business Studies",
        "Economics",
        "Applied Maths",
        "Entrepreneurship",
        "Psychology",
        "Sociology",
        "Political Science",
        "History",
        "Geography",
        "Home Science",
        "Legal Studies",
        "English Core",
        "English Elective",
        "Physical Education",
        "Fine Arts"
    ]
};

export const CITY_TO_LOCATIONS_DATA: Record<string, string[]> = {
  "Ahmedabad": ["Ahmedabad Cantonment", "Alam Roza", "Ambawadi", "Ambli", "Amraiwadi", "Asarwa Chakla", "Asarwa", "Aslali", "Ayojan Nagar", "Badarkha", "Bahiyal", "Bapunagar", "Bardolpura", "Behrampura", "Bhadaj", "Bhadra", "Bhairavnath Road", "Bodakdev", "Bopal", "CG Road", "CTM Char Rasta", "CTM", "Chaloda", "Chandkheda", "Chandlodiya", "Changodar", "Dabhoda", "Dani Limbada", "Dariapur", "Delhi Chakla", "Delhi Darwaja", "Detroj", "Dhandhuka", "Dholka", "Drive In Road", "Dudheshwar Road", "Dudheshwar", "Ellis Bridge", "Gandhi Road", "Geeta Mandir Road", "Geeta Mandir", "Ghatlodia", "Gheekanta Road", "Gheekanta", "Ghodasar", "Girdharnagar", "Gomtipur", "Gota", "Gulbai Tekra", "Gurukul", "Hansol", "Hatkeshwar", "Income Tax", "India Colony", "Indrapuri", "Isanpur", "Jagatpur", "Jamalpur", "Jasodanagar", "Jawahar Chowk", "Jholapur", "Jodhpur", "Juhapura", "Juna Wadaj", "Kalupur", "Kalyanpura", "Kankaria Road", "Kankaria", "Kathwada", "Khadia", "Khamasa", "Khanpur", "Kharna", "Khodiyarnagar", "Khokhra", "Krishnanagar", "Kubernagar", "Lambha", "Madhupura", "Makarba", "Manek Chowk", "Maninagar", "Meghani Nagar", "Memnagar", "Mirzapur Road", "Mirzapur", "Mithakali", "Motera", "Nandej", "Naranpura", "Naroda GIDC", "Naroda Road", "Naroda", "Narodamuthiya", "Narol", "Nava Vadaj", "Navarangpura", "Nikol", "Nirnay Nagar", "Noblenagar", "Odhav GIDC", "Odhav Road", "Odhav", "Paldi", "Pankore Naka", "Patharkuva", "Polarpur", "Prahlad Nagar", "Raipur", "Rajpur Gomtipur", "Rajpur", "Rakhial", "Ramol", "Ranip", "Ranna Park", "Ratan Pole", "Revdi Bazaar", "Sabarmati", "Saijpur Bogha", "Saijpur", "Sanand", "Sarangpur", "Saraspur", "Sardar Nagar", "Sarkhej", "Sarkhej Gandhinagar Highway", "Satellite Road", "Satellite", "Science City Road", "Shah Alam Road", "Shahibaug Road", "Shahibaug", "Shahpur", "Shardanagar", "Shastri Nagar", "Shela", "Shilaj", "Sindhu Bhavan Road", "Sola Road", "Sola", "Subhash Bridge", "Sukhrampura", "Tavdipura", "Teen Darwaja", "Thakkarbapa Nagar", "Thaltej", "Usmanpura", "Vasna", "Vastral", "Vastrapur", "Vatva GIDC", "Vatva", "Vejalpur", "Viramgam", "Walled City"],
  "Ajmer": ["Civil Lines", "Vaishali Nagar", "Adarsh Nagar", "Panchsheel Nagar", "Shastri Nagar", "Ganj", "Madar Gate", "Dargah Area", "Pushkar Road", "Ana Sagar Link Road", "Beawar Road"],
  "Amritsar": ["Ranjit Avenue", "Lawrence Road", "Mall Road", "Green Avenue", "White Avenue", "Majitha Road", "Batala Road", "Ram Tirath Road", "Putligarh", "Islamabad Area", "Verka", "Chheharta", "Basant Avenue"],
  "Anand": ["Vallabh Vidyanagar", "Bakrol", "Karamsad", "Lambhvel", "Jitodia", "Chikhodra", "Mogar", "Gamdi", "Sardar Ganj", "Iscon Area"],
  "Armoor": ["Bus Stand Area", "Ambedkar Chowk", "Gandhi Nagar", "Shanti Nagar", "Bypass Road", "Market Road", "Teachers Colony", "Housing Board Colony"],
  "Aurangabad": ["CIDCO", "Garkheda", "Kranti Chowk", "Osmanpura", "Ulkanagari", "Jalna Road", "Waluj", "Mukundwadi", "Harsul", "Paithan Road", "Bajaj Nagar"],
  "Bareilly": ["Civil Lines", "Model Town", "Rajendra Nagar", "Izatnagar", "Karamchari Nagar", "Dohra Road", "Green Park Colony", "Shyam Ganj", "Subhash Nagar", "Prem Nagar", "Alakhnath", "Pilibhit Bypass Road", "Faridpur Road"],
  "Belagavi": ["Tilakwadi", "Shahapur", "Vadgaon", "Camp Area", "Hanuman Nagar", "Ashok Nagar", "Hindwadi", "Angol", "Mahantesh Nagar"],
  "Belgaum": ["Rani Chennamma Nagar", "Bhagya Nagar", "Ramteerth Nagar", "Fort Road", "College Road", "Nehru Nagar", "Malmaruti Extension"],
  "Bangalore": ["Adugodi", "Agara", "Agram", "Airport Road", "Amruthahalli", "Anand Nagar", "Anjanapura", "Arekere", "Attibele", "Austin Town", "BTM Layout", "Banaswadi", "Bannerghatta Road", "Bannerghatta", "Basavanagudi", "Basaveshwar Nagar", "Begur", "Bellandur", "Benson Town", "Bettahalasur", "Bidadi", "Bidare Agrahara", "Bidrahalli", "Billekahalli", "Bommanahalli", "Bommasandra", "Byatarayanapura", "C.V. Raman Nagar", "Chamarajpet", "Chandapura", "Channasandra", "Chikkalasandra", "Chikkamagaluru", "Cleveland Town", "Cooke Town", "Cox Town", "Cubbon Park", "Dasarahalli", "Devanahalli", "Devinagar", "Dharmaram", "Doddaballapur", "Doddakallasandra", "Domlur", "Dooravani Nagar", "Ejipura", "Electronic City", "Fraser Town", "Gandhi Nagar", "Ganganagar", "Gattigere", "Gollahalli", "Gottigere", "Govindaraja Nagar", "Gowdanapalya", "H.A.L. Old Airport Road", "HBR Layout", "HMT Layout", "HSR Layout", "Hennur Road", "Hennur", "Herohalli", "Hesaraghatta Main Road", "Hesaraghatta", "Hoodi", "Horamavu", "Hosakerehalli", "Hosur Road", "Hulimavu", "Indiranagar", "JP Nagar", "Jakkur", "Jalahalli", "Jayamahal", "Jayanagar", "Jnanabharathi", "Kadugodi", "Kadugodi Plantation", "Kaggadasapura", "Kaggalipura", "Kakolu", "Kalkere", "Kalyan Nagar", "Kamakshipalya", "Kammanahalli", "Kanakapura Road", "Kanchenahalli", "Kannamangala", "Kasturi Nagar", "Kathriguppe", "Kempegowda International Airport", "Kengeri", "Kengeri Satellite Town", "Kodichikkanahalli", "Kogilu", "Konanakunte", "Kothanur", "Kothnur Dinne", "Krishnarajapuram", "Kumaraswamy Layout", "Kumbalgodu", "Kundalahalli", "Langford Town", "Lavelle Road", "Lottegollahalli", "MCECHS Layout", "Madiwala", "Magadi Road", "Mahadevapura", "Majestic", "Marathahalli", "Maruthi Sevanagar", "Mathikere", "Medahalli", "Mysore Road", "NRI Layout", "Nagadevanahalli", "Nagarbhavi", "Nagasandra", "Nandi Hills", "Nandini Layout", "New Thippasandra", "Old Airport Road", "Old Madras Road", "Padmanabhanagar", "Palace Road", "Panduranga Nagar", "Peenya", "Puttenahalli", "R.T. Nagar", "R.V. College of Engineering", "RMV Extension", "Race Course Road", "Rachenahalli", "Rajajinagar", "Rajanukunte", "Ramamurthy Nagar", "Ramasandra", "Richmond Road", "Richmond Town", "Sadashivanagar", "Sahakar Nagar", "Sampangiram Nagar", "Sanjay Nagar", "Sarjapur Road", "Sarjapur", "Seshadripuram", "Shankarapura", "Shivajinagar", "Silk Board", "Singapura", "Singasandra", "Soladevanahalli", "Srinagara", "St. Marks Road", "Subramanyapura", "Sulikere", "Sultanpalya", "Tavarekere", "Thigalarapalya", "Thindlu", "Thippasandra", "Tumkur Road", "Ulsoor", "Uttarahalli", "Varthur", "Vasanth Nagar", "Vidyaranyapura", "Vijayanagar", "Vimanapura", "Virgonagar", "Viswaneedam", "Viveka Nagar", "Whitefield", "Williams Town", "Wilson Garden", "Yelahanka", "Yelahanka New Town", "Yeshwanthpur"],
  "Bhilai": ["Supela", "Smriti Nagar", "Nehru Nagar", "Risali", "Durg Road", "Civic Centre", "Bhilai Nagar", "Power House", "Ruabandha"],
  "Bhilwara": ["Shastri Nagar", "Azad Nagar", "Subhash Nagar", "Indira Colony", "Bapunagar", "Sangam Nagar", "Gandhi Nagar", "Kareda Chouraha"],
  "Bhiwadi": ["Alwar Bypass Road", "Chopanki", "UIT Sector 2", "UIT Sector 3", "Phase 1", "Phase 2", "Phase 3", "Capital Mall Area", "Tapukara Road"],
  "Bhopal": ["10 No Market", "Airport Road", "Anand Nagar Extension", "Anand Nagar", "Arera Colony", "Ashoka Garden", "Awadhpuri", "Ayodhya Bypass", "BHEL Township", "Bagh Mughalia", "Bairagarh Cantt", "Bairagarh Chichali", "Bairagarh Kalan", "Bairagarh", "Barkheda", "Basant Kunj", "Bawadia Kalan", "Berasia", "Berasiya Road", "Bhopal Talkies Area", "Bittan Market", "Chanchal Chowk", "Char Imli", "Chuna Bhatti", "Gandhi Nagar", "Govindpura", "Gufa Mandir", "Gulmohar Colony", "Habibganj", "Hamidia Road", "Hoshangabad Road", "Idgah Hills", "Indrapuri", "JP Nagar", "Jail Road", "Jawahar Chowk", "Kamla Park", "Karishma Hills", "Karond", "Kasturba Nagar", "Katara Hills", "Kohefiza", "Kolar Road", "Lalghati", "MP Nagar", "Mandideep", "Misrod", "Narela Shankari", "Nehru Nagar", "New Market", "Nizamuddin Colony", "North TT Nagar", "Patel Nagar", "Peer Gate", "Piplani", "Ratibad", "Roshanpura", "Saket Nagar", "Shahpura", "Shyamla Hills", "South TT Nagar", "Station Road", "Subhash Nagar", "T. T. Nagar", "Talaiya"],
  "Bhubaneswar": ["Patia", "Chandrasekharpur", "Nayapalli", "Jayadev Vihar", "Kharavel Nagar", "Saheed Nagar", "Rasulgarh", "Mancheswar", "Old Town", "Baramunda", "Dumduma", "Kalinga Nagar"],
  "Bilaspur": ["Vyapar Vihar", "Sarkanda", "Mangla", "Torwa", "Tifra", "Nehru Nagar", "Tikrapara", "Gandhi Chowk"],
  "Bokaro": ["Sector 4", "Sector 5", "Sector 6", "Sector 9", "Sector 12", "Chas", "Co-operative Colony", "City Centre", "Balidih"],
  "Burdwan": ["Golapbag", "Nutanpally", "Sripally", "Khosbagan", "Alamganj", "Vivekananda College Area", "Court Area", "Baburbag"],
  "Chandigarh": ["Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 7", "Sector 8", "Sector 9", "Sector 10", "Sector 11", "Sector 15", "Sector 17", "Sector 22", "Sector 23", "Sector 26", "Sector 27", "Sector 30", "Sector 31", "Sector 34", "Sector 35", "Sector 39", "Sector 41", "Sector 45", "Sector 47", "Sector 49", "Sector 50", "Sector 52", "Sector 53", "Sector 55", "Sector 56", "Sector 61", "Sector 62", "Sector 63", "Sector 64", "Sector 66", "Sector 67", "Sector 71", "Sector 76", "Sector 77", "Sector 79", "Sector 80", "Sector 82", "Sector 85", "Sector 86", "Sector 90", "Sector 91", "Sector 92", "Mani Majra", "Khuda Alisher", "Mauli Jagran"],
  "Chennai": ["Adambakkam", "Adyar", "Alandur", "Alapakkam", "Alwarpet", "Ambattur", "Aminjikarai", "Anna Nagar", "Anna Salai", "Annanur", "Arumbakkam", "Ashok Nagar", "Avadi", "Ayanavaram", "Besant Nagar", "Broadway", "Chintadripet", "Chitlapakkam", "Choolai", "Choolaimedu", "Chromepet", "Egmore", "Ekkattuthangal", "Ennore", "Foreshore Estate", "George Town", "Gopalapuram", "Guindy", "Injambakkam", "Iyappanthangal", "Iyyapanthangal", "Jafferkhanpet", "Jalladianpet", "K.K. Nagar", "Kadappakkam", "Kallikuppam", "Kanathur", "Kandanchavadi", "Kandigai", "Kangeyam", "Kattupakkam", "Kazhipattur", "Keelkattalai", "Kilpauk", "Kodambakkam", "Kodungaiyur", "Kolathur", "Kompakkam", "Kottivakkam", "Kotturpuram", "Kovalam", "Kovilambakkam", "Kovur", "Koyambedu", "Kundrathur", "Madambakkam", "Madhavaram Milk Colony", "Madhavaram", "Madipakkam", "Maduravoyal", "Manali", "Manapakkam", "Mangadu", "Mannady", "Maraimalai Nagar", "Medavakkam", "Meenambakkam", "Mogappair", "Moolakadai", "Mount Road", "Mugalivakkam", "Mylapore", "Nanganallur", "Nanmangalam", "Nerkundram", "Nesapakkam", "Nolambur", "Nungambakkam", "Old Mahabalipuram Road (OMR)", "Otteri", "Padur", "Palavakkam", "Pallavaram", "Pallikaranai", "Pammal", "Perambur", "Perumbakkam", "Perungalathur", "Perungudi", "Poonamallee", "Porur", "Purasaiwakkam", "Puthagaram", "Puzhal", "Puzhuthivakkam", "Red Hills", "Royapettah", "Royapuram", "Saidapet", "Saligramam", "Santhome", "Selaiyur", "Semmancheri", "Shenoy Nagar", "Sholinganallur", "Sithalapakkam", "Sowcarpet", "SriramNagar", "St. Thomas Mount", "T Nagar", "Tambaram", "Taramani", "Teynampet", "Thirumazhisai", "Thirumullaivoyal", "Thiruneermalai", "Thiruninravur", "Thiruvanmiyur", "Thiruverkadu", "Thoraipakkam", "Tindivanam", "Tondiarpet", "Ullagaram", "Urapakkam", "Vadapalani", "Valasaravakkam", "Vanagaram", "Vandalur", "Velachery", "Velappanchavadi", "Vengaivasal", "Villivakkam", "Virugambakkam", "Vyasarpadi", "Washermanpet", "West Mambalam"],
  "Coimbatore": ["RS Puram", "Gandhipuram", "Saibaba Colony", "Peelamedu", "Singanallur", "Ukkadam", "Town Hall", "Saravanampatti", "Kalapatti", "Vadavalli", "Kovaipudur", "Kuniamuthur", "Ganapathy", "Thudiyalur", "Avinashi Road", "Sulur"],
  "Cuttack": ["College Square", "Buxi Bazaar", "Badambadi", "CDA Sector 6", "CDA Sector 7", "CDA Sector 10", "Jobra", "Choudwar Road", "Link Road", "Tulasipur", "Mangalabag"],
  "Dehradun": ["Rajpur Road", "Jakhan", "Ballupur", "Clement Town", "Sahastradhara Road", "Patel Nagar", "Nehru Colony", "Vasant Vihar", "Prem Nagar", "ISBT Area", "Dalanwala", "Race Course", "Karbari Grant", "Selakui", "Mussoorie Road"],
  "Delhi": ["Anand Niketan", "Anand Parbat", "Ashok Vihar", "Burari", "Chattarpur", "Civil Lines", "Connaught Place", "Defence Colony", "Dwarka Mor", "Dwarka", "Greater Kailash", "Green Park", "Hauz Khas", "IP Extension", "Janakpuri", "Jangpura", "Jor Bagh", "Kalkaji", "Karampura", "Lajpat Nagar", "Malviya Nagar", "Mayur Vihar", "Mukherjee Nagar", "Narela", "Panchsheel Park", "Paschim Puri", "Paschim Vihar", "Pitampura", "Preet Vihar", "Rajouri Garden", "Rohini", "Safdarjung Enclave", "Sainik Farms", "Saket", "Shahpur Jat", "Shalimar Bagh", "Uttam Nagar", "Vasant Kunj", "Vasant Vihar", "Vikaspuri", "Yamuna Vihar"],
  "Dhanbad": ["Bank More", "Hirapur", "Jharia", "Katras", "Saraidhela", "Barwadda", "Govindpur", "Baliapur", "Kusunda", "Housing Colony"],
  "Dharwad": ["Vidyanagar", "Saptapur", "Kalyan Nagar", "Malmaddi", "Jubilee Circle", "Hosayellapur", "Gopankoppa", "Lakamanahalli", "Navanagar"],
  "Faridabad": ["Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6", "Sector 7", "Sector 8", "Sector 9", "Sector 10", "Sector 11", "Sector 12", "Sector 13", "Sector 14", "Sector 15", "Sector 16", "Sector 17", "Sector 18", "Sector 19", "Sector 20", "Sector 21", "Sector 22", "Sector 23", "Sector 24", "Sector 25", "Sector 26", "Sector 27", "Sector 28", "Sector 29", "Sector 30", "Sector 31", "Sector 32", "Sector 33", "Sector 34", "Sector 35", "Sector 36", "Sector 37", "Sector 38", "Sector 39", "Sector 40", "Sector 41", "Sector 42", "Sector 43", "Sector 44", "Sector 45", "Sector 46", "Sector 47", "Sector 48", "Sector 49", "Sector 50", "Sector 51", "Sector 52", "Sector 53", "Sector 54", "Sector 55", "Sector 56", "Sector 57", "Sector 58", "Sector 59", "Sector 60", "Sector 61", "Sector 62", "Sector 63", "Sector 64", "Sector 65", "Sector 66", "Sector 67", "Sector 68", "Sector 69", "Sector 70", "Sector 71", "Sector 72", "Sector 73", "Sector 74", "Sector 75", "Sector 76", "Sector 77", "Sector 78", "Sector 79", "Sector 80", "Sector 81", "Sector 81A", "Sector 82", "Sector 83", "Sector 84", "Sector 85", "Sector 86", "Sector 87", "Sector 88", "Sector 89", "Sector 90", "Sector 91", "NIT"],
  "Gandhinagar": ["Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6", "Sector 7", "Sector 8", "Sector 9", "Sector 10", "Sector 11", "Sector 12", "Sector 13", "Sector 14", "Sector 15", "Sector 16", "Sector 17", "Sector 18", "Sector 19", "Sector 20", "Sector 21", "Sector 22", "Sector 23", "Sector 24", "Sector 25", "Sector 26", "Sector 27", "Sector 28", "Sector 29", "Sector 30"],
  "Gangtok": ["Deorali", "Tadong", "Ranipool", "Development Area", "Upper Sichey", "Lower Sichey", "Tibet Road", "Arithang", "Burtuk"],
  "Ghaziabad": ["Ashok Nagar", "Crossing Republik", "Gandhi Nagar", "Ghantaghar", "Govindpuram", "Indirapuram", "Kaushambi", "Kavi Nagar", "Loni", "Mohan Nagar", "Nehru Nagar", "Patel Nagar", "Pratap Vihar", "Raj Nagar Extension", "Raj Nagar", "Rajendra Nagar", "Sanjay Nagar", "Shalimar Garden", "Shastri Nagar", "Siddharth Vihar", "Surya Nagar", "Vaishali", "Vasundhara", "Vijay Nagar", "Wave City NH24"],
  "Goa": ["Panjim", "Mapusa", "Margao", "Vasco da Gama", "Ponda", "Candolim", "Calangute", "Baga", "Anjuna", "Porvorim", "Dona Paula"],
  "Gorakhpur": ["Golghar", "Civil Lines", "Basharatpur", "Rustampur", "Medical College Road", "Chargawan", "Rapti Nagar", "Taramandal", "Shahpur"],
  "Greater Noida": ["Alpha 1", "Alpha 2", "Beta 1", "Beta 2", "Chi 1", "Chi 2", "Chi 3", "Chi 4", "Chi 5", "Delta 1", "Delta 2", "Delta 3", "Delta 4", "Eco Village 1", "Eco Village 2", "Eco Village 3", "Eco Village 4", "Gamma 1", "Gamma 2", "Knowledge Park 1", "Knowledge Park 2", "Knowledge Park 3", "Knowledge Park 4", "MU", "Noida Extension", "Omicron 1", "Omicron 2", "Omicron 3", "Omega", "Pari Chowk", "PI 1", "PI 2", "PI 3", "Sigma 1", "Sigma 2", "Sigma 3", "Sigma 4", "Swarn Nagari", "Techzone 1", "Techzone 2", "Techzone 4", "Techzone 5", "Xu 1", "Xu 2", "Yamuna Expressway", "Zeta 1", "Zeta 2"],
  "Gulbarga": ["Super Market Area", "Station Road", "Sedam Road", "Shah Bazar", "Jewargi Road", "Vidyanagar", "Veeresh Nagar", "Old City"],
  "Guntur": ["Brodipet", "Arundelpet", "Lakshmipuram", "Brindavan Gardens", "Pattabhipuram", "Koritepadu", "Syamalanagar", "Chandramouli Nagar"],
  "Gurgaon": ["DLF Phase 1", "DLF Phase 2", "DLF Phase 3", "DLF Phase 4", "DLF Phase 5", "IMT Manesar", "Maruti Kunj", "Palam Vihar", "Sushant Lok 1", "Sushant Lok 2", "Sushant Lok 3", "Sector 1", "Sector 3", "Sector 4", "Sector 5", "Sector 6", "Sector 7", "Sector 8", "Sector 9", "Sector 9A", "Sector 10", "Sector 10A", "Sector 11", "Sector 12", "Sector 12A", "Sector 13", "Sector 14", "Sector 15", "Sector 17", "Sector 18", "Sector 21", "Sector 22", "Sector 23", "Sector 23A", "Sector 24", "Sector 25", "Sector 27", "Sector 28", "Sector 30", "Sector 31", "Sector 33", "Sector 36", "Sector 37", "Sector 37C", "Sector 37D", "Sector 38", "Sector 39", "Sector 40", "Sector 41", "Sector 42", "Sector 43", "Sector 45", "Sector 46", "Sector 47", "Sector 48", "Sector 49", "Sector 50", "Sector 51", "Sector 52", "Sector 53", "Sector 54", "Sector 55", "Sector 56", "Sector 57", "Sector 58", "Sector 59", "Sector 60", "Sector 61", "Sector 62", "Sector 63", "Sector 65", "Sector 66", "Sector 67", "Sector 68", "Sector 69", "Sector 70", "Sector 70A", "Sector 71", "Sector 72", "Sector 73", "Sector 76", "Sector 77", "Sector 79", "Sector 81", "Sector 82", "Sector 82A", "Sector 83", "Sector 84", "Sector 85", "Sector 86", "Sector 88", "Sector 89", "Sector 90", "Sector 91", "Sector 92", "Sector 93", "Sector 95", "Sector 102", "Sector 103", "Sector 104", "Sector 105", "Sector 107", "Sector 108", "Sector 109", "Sector 110", "Sector 111", "Sector 112", "Sector 113"],
  "Guwahati": ["Adabari", "Azara", "Basistha", "Beharbari", "Beltola", "Bhangagarh", "Bhetapara", "Boragaon", "Borjhar", "Chandmari", "Christian Basti", "Dispur", "GS Road", "Ganeshguri", "Garchuk", "Geetanagar", "Hatigaon", "Jalukbari", "Jyotikuchi", "Kahilipara", "Khanapara", "Kharghuli", "Lal Ganesh", "Lokhra", "Maligaon", "Narengi", "Noonmati", "Panjabari", "Patharquerry", "RG Baruah Road", "Rehabari", "Silpukhuri", "Six Mile", "Ulubari", "Uzan Bazar", "Zoo Road"],
  "Gwalior": ["City Centre", "Lashkar", "Thatipur", "Morar", "Govindpuri", "Patel Nagar", "Phool Bagh", "Maharajpura", "Hazira", "Alkapuri", "Dabra Road"],
  "Howrah": ["Shibpur", "Liluah", "Bally", "Kadamtala", "Salkia", "Santragachi", "Belur", "Avani Riverside Area", "Pilkhana"],
  "Hyderabad": ["A. S. Rao Nagar", "Abids", "Adibatla", "Aghapura", "Almasguda", "Alwal", "Amberpet", "Ameerpet", "Asif Nagar", "Attapur", "Bachupally", "Badangpet", "Bahadurpura", "Bandlaguda Jagir", "Banjara Hills", "Basheerbagh", "Beeramguda", "Boduppal", "Bowenpally", "Buddha Nagar", "Chandanagar", "Chandrayangutta", "Dandamudi Enclave", "Dilsukhnagar", "Gachibowli", "Gajularamaram", "Gopanpally", "Habsiguda", "Hafeezpet", "Hayathnagar", "Himayatnagar", "Jeedimetla", "Jubilee Hills", "Kachiguda", "Kanchan Bagh", "Karmanghat", "Karwan", "Khajaguda", "Kompally", "Kondapur", "Kothapet", "Kowkoor", "Kukatpally", "Kushaiguda", "LB Nagar", "Lingampally", "Madeenaguda", "Madhapur", "Malakpet", "Manikonda", "Mansoorabad", "Medchal", "Miyapur", "Moti Nagar", "Nacharam", "Nagole", "Nallagandla", "Nampally", "Narsingi", "Neredmet", "Nizampet", "Osmannagar", "Padmarao Nagar", "Patancheru", "Peerzadiguda", "Pragathi Nagar", "Quthbullapur", "RTC X Roads", "Raidurg", "Rajendra Nagar", "Rangareddy", "Safilguda", "Saidabad", "Sanath Nagar", "Secunderabad Cantonment", "Secunderabad", "Serilingampally", "Shaikpet", "Shamshabad", "Sitaphalmandi", "Somajiguda", "Suraram", "Tellapur", "Toli Chowki", "Uppal", "Upparapalli", "Vanasthalipuram", "Warasiguda", "West Marredpally", "Yousufguda"],
  "Indore": ["AB Road", "Ambedkar Nagar", "Azad Nagar", "Bada Bangarda", "Bhanwarkuan", "Bicholi Mardana", "Bijalpur", "Chandan Nagar", "Chandra Nagar", "Dewas Naka", "Geeta Bhawan", "Gulmohar Colony", "IDA Scheme No 134", "Jhalariya", "Kanadia Main Road", "Khajrana", "Khandwa Road", "LIG Colony", "MR 10 Road", "Mahalaxmi Nagar", "Malviya Nagar", "Malwa County", "Manglia", "Navlakha", "New Rani Bagh", "Nipania", "Niranjanpur", "Palasia", "Pipliyahana", "Rajendra Nagar", "Rau Colony", "Rau", "Saket Nagar", "Sangam Nagar", "Satya Sai Chouraha", "Scheme No 114", "Scheme No 54", "Scheme No 78", "Silicon City", "Simrol", "South Tukoganj", "Sukhliya", "Super Corridor", "Talawali Chanda", "Ujjain Road", "Vaishali Nagar", "Vijay Nagar"],
  "Jabalpur": ["Napier Town", "Wright Town", "Vijay Nagar", "Gwarighat", "Adhartal", "Madan Mahal", "Tilwara", "Garha", "Cherital", "Ranjhi"],
  "Jaipur": ["C-Scheme", "Civil Lines", "Malviya Nagar", "Vaishali Nagar", "Bani Park", "Jagatpura", "Raja Park", "Shyam Nagar", "Mansarovar", "Tonk Road", "Lal Bahadur Nagar", "Shivaji Nagar", "Nirman Nagar", "Sanganer", "Jhotwara", "Gopalpura Bypass", "Durgapura", "Pratap Nagar", "Ajmer Road", "Sikar Road", "Sirsi Road", "Bapu Nagar", "Chitrakoot", "Vidhyadhar Nagar", "Anandpuri", "Mahaveer Nagar", "Bajaj Nagar", "Ambabari", "Kukas", "Amer", "JLN Marg", "Patrakar Colony", "Model Town", "Mahal Road", "Hasanpura", "Gokulpura", "Nehru Nagar", "Adarsh Nagar", "Tilak Nagar", "Kanota", "Sodala", "Murlipura", "Rukanpura", "Paldi Meena", "Saraswati Nagar", "Rambagh", "Barkat Nagar", "Gangapole", "Harmada", "Vishwakarma Industrial Area", "Keshopura", "Shastri Nagar", "Hanuman Nagar", "Sunder Nagar", "Mansarovar Extension", "Jaisinghpura", "Kalwar Road", "Phulera", "Dudu", "Chomu", "Kotputli", "Bassi", "Bagru", "Chaksu"],
  "Jalandhar": ["Model Town", "Civil Lines", "Urban Estate Phase 1", "Urban Estate Phase 2", "Basti Sheikh", "Basti Bawa Khel", "Rama Mandi", "Cantt Road", "Mithapur", "Nakodar Road"],
  "Jalgaon": ["MIDC Area", "Zilha Peth", "Baliram Peth", "Ring Road", "Pimprala", "Mehrun", "Khandesh Nagar", "Deopur", "Shivaji Nagar"],
  "Jammu": ["Gandhi Nagar", "Trikuta Nagar", "Channi Himmat", "Talab Tillo", "Janipur", "Bohri", "Bakshi Nagar", "Shastri Nagar", "Bari Brahmana"],
  "Jamnagar": ["Patel Colony", "Gulab Nagar", "Indira Marg", "Saru Section Road", "Ranjit Sagar Road", "Digvijay Plot", "Jogvad", "GIDC Phase 1"],
  "Jodhpur": ["Ratanada", "Sardarpura", "Chopasni Road", "Paota", "Mandore", "Basni", "Shastri Nagar", "Pal Road", "Pratap Nagar"],
  "Jorhat": ["Tarajan", "Garali", "Pulibor", "Kenduguri", "Cinnamara", "Rowriah", "Chandan Nagar", "A.T. Road Area"],
  "Kakinada": ["Sarpavaram", "Jagannaickpur", "Bhanugudi", "Ramanayyapeta", "Ashok Nagar", "Gajuwaka Road Area", "Indrapalem"],
  "Kalyan": ["Kalyan East", "Kalyan West", "Khadakpada", "Gandhare", "Vithalwadi", "Shahad", "Ambivli", "Titwala Road Area"],
  "Kanpur": ["Ansari Marg", "Ansari Road", "Ary Nagar", "Barra", "Bethou", "Bharath Nagar", "Birhana Road", "Bypass Road", "Chunniganj", "Civil Lines Extension", "Civil Lines", "Dada Nagar", "Faizabad Road Colony", "Faizullahgz", "Gandhi Puram", "Govind Nagar", "Guava Khand", "Hindon X Road", "Jajmau", "Kakadeo", "Kalyanpur", "Kavila Nagar", "Kidwai Nagar", "Lal Bangla", "Lala Lajpat Rai Marg", "Meston Road", "Mitra College Road", "Mitraon", "Nandi Bazaar", "Naveen Market", "Nehru Nagar", "Nirala Nagar", "Niwari Nala", "Padampur", "Quest Khand", "Railway Hospital Colony", "Ratan Lal Nagar", "Rawatpur Railway Colony", "Rawatpur", "Rivalganj", "Saket Nagar", "Sarsaiya", "Sharda Nagar", "Shastri Nagar", "Shehzada Ganj", "Sihani Gate", "Swarn Jayanti Nagar", "Swaroop Nagar", "Tagore Marg", "Teliyarganj", "Tilak Nagar", "Vishnupuri"],
  "Khanna": ["GT Road Area", "Model Town", "New Grain Market", "Civil Lines", "Green Avenue", "Ward No 9", "Samrala Road"],
  "Cochin": ["Kakkanad", "Edappally", "Kaloor", "Palarivattom", "Vyttila", "Panampilly Nagar", "Fort Kochi", "Mattancherry", "Aluva", "Tripunithura", "Kadavanthra", "Marine Drive", "Thevara", "Thrippunithura", "Kalamassery", "Cheranallur"],
  "Kolkata": ["Agarpara", "Alipore", "Amherst Street", "Andul", "Baghajatin", "Baguiati", "Ballygunge", "Bansdroni", "Baranagar", "Barrackpore", "Behala", "Belghoria", "Beliaghata", "Bidhannagar", "Cossipore", "Dum Dum", "EM Bypass", "Ganguli Bagan", "Garia", "Howrah", "Jadavpur", "Kankinara", "Kasba", "Lake Gardens", "Lake Town", "Maheshtala", "Manicktala", "Mukundapur", "Nagerbazar", "Naktala", "Narendrapur", "Narkel Bagan", "Nathpara", "New Town", "Picnic Garden", "Rajarhat Gopalpur", "Rajarhat", "Regent Park", "Salt Lake", "Sealdah", "Sodepur", "Sonarpur", "Taltala", "Thakurpukur", "Tollygunge", "Topsia", "Ultadanga"],
  "Kolhapur": ["Tarabai Park", "Shahupuri", "Rankala", "Ujalaiwadi", "Kadamwadi", "Rajarampuri", "Laxmipuri", "Shiroli MIDC", "Kalamba", "Jaysingpur Road"],
  "Kota": ["Talwandi", "Mahaveer Nagar", "Jawahar Nagar", "Vigyan Nagar", "Dadabari", "Indira Vihar", "Kunhadi", "Rangbari", "Nayapura", "Gumanpura"],
  "Latur": ["Udgir Road", "Ausa Road", "Barshi Road", "Old MIDC", "Renapur Naka", "Dayanand Gate", "Signal Camp", "Ram Nagar"],
  "Leh": ["Main Market", "Choglamsar", "Spituk", "Shey", "Thiksey", "Saboo", "Phyang", "Skara", "Changspa"],
  "Liluah": ["Belur Math Road", "Liluah Station Area", "G.T. Road", "Don Bosco Area", "Salkia Extension"],
  "Lucknow": ["Abidnagar", "Aerocity", "Aishbagh", "Alambagh", "Aliganj", "Anand Nagar", "Ashfaq Colony", "Ashiyana Colony", "Bakshi Ka Talab", "Bank Road", "Barabanki Road", "Baradari", "Bharat Nagar", "Bhootnath Market", "Charbagh", "Chinhat", "Dubagga", "Golbagh", "Gomti Nagar Extension", "Gomti Nagar", "Hazaratganj", "Indira Nagar", "Infront", "Jangali Nagri", "Jankipuram", "Juggi-Budhi", "Kaiserbagh", "Kalyanpur", "Kapoorthala", "Kashiya Nagar", "Khurram Nagar", "Kolkata Road", "Krishna Nagar", "Lucknow Cantt.", "Mahanagar", "Malakpet", "Malviya Nagar", "Nirala Nagar", "Pandey Nagar", "Pandu Nagar", "Rajajipuram", "Rajendra Nagar", "Rajiv Gandhi Puram", "Rani Laxmi Bai Marg", "Ravindrapalli", "Rudra Mahal", "Saadatganj", "Saket Nagar", "Samta Nagar", "Shaheed Path", "Sheetal Nagar", "Shram Nagar", "Sitapur Road", "Sushant Golf City", "Swaroop Nagar", "Tagore Marg", "Takrohi Bazaar", "Talkatora", "Ujariyaon", "Vishwas Khand", "Volga Bazaar", "Vrindavan Yojna"],
  "Ludhiana": ["Model Town", "Civil Lines", "Sarabha Nagar", "Dugri", "Pakhowal Road", "Ferozepur Road", "Haibowal", "BRS Nagar", "Jampur", "Industrial Area A", "Industrial Area B", "Gill Road", "Ghumar Mandi", "Sunet", "Shimlapuri"],
  "Machillipatnam": ["Pedana Road", "Bandar Road", "Main Market Area", "Guduru Road", "Koneru Centre", "Auto Nagar", "Poleramma Temple Area"],
  "Madurai": ["Anna Nagar", "KK Nagar", "Tallakulam", "Ellis Nagar", "Arapalayam", "Teppakulam", "Villapuram", "Avaniyapuram", "Tirupparankundram", "Bypass Road", "Thirunagar"],
  "Mangalore": ["Hampankatta", "Kadri", "Bejai", "Kankanady", "Balmatta", "Falnir", "Urwa", "Surathkal", "Kulai", "Panambur", "Derebail"],
  "Manipal": ["End Point Road", "Eshwar Nagar", "Madhav Nagar", "Tiger Circle Area", "Udupi Road Area", "MIT Campus Area", "Ananth Nagar"],
  "Meerut": ["Shastri Nagar", "Pallavpuram", "Ganga Nagar", "Defence Colony", "Kanker Khera", "Saket", "Modipuram", "Mawana Road", "Shatabdi Nagar", "Surajkund", "Civil Lines", "Jagriti Vihar", "Garh Road", "Partapur"],
  "Mohali": ["Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6", "Sector 7", "Sector 8", "Sector 9", "Sector 10", "Sector 11", "Sector 12", "Sector 13", "Sector 14", "Sector 15", "Sector 16", "Sector 17", "Sector 18", "Sector 19", "Sector 20", "Sector 21", "Sector 22", "Sector 23", "Sector 24", "Sector 25", "Sector 26", "Sector 27", "Sector 28", "Sector 29", "Sector 30", "Sector 31", "Sector 32", "Sector 33", "Sector 34", "Sector 35", "Sector 36", "Sector 37", "Sector 38", "Sector 39", "Sector 40", "Sector 41", "Sector 42", "Sector 43", "Sector 44", "Sector 45", "Sector 46", "Sector 47", "Sector 48", "Sector 49", "Sector 50", "Sector 51", "Sector 52", "Sector 53", "Sector 54", "Sector 55", "Sector 56", "Sector 57", "Sector 58", "Sector 59", "Sector 60", "Sector 61", "Sector 62", "Sector 63", "Sector 64", "Sector 65", "Sector 66", "Sector 67", "Sector 68", "Sector 69", "Sector 70", "Sector 71", "Sector 72", "Sector 73", "Sector 74", "Sector 75", "Sector 76", "Sector 77", "Sector 78", "Sector 79", "Sector 80", "Sector 81", "Sector 82", "Sector 83", "Sector 84", "Sector 85", "Sector 86", "Sector 87", "Sector 88", "Sector 89", "Sector 90", "Sector 91", "Sector 92", "Sector 93", "Sector 94", "Sector 95", "Sector 96", "Sector 97", "Sector 98", "Sector 99", "Sector 100", "Sector 101", "Sector 102", "Sector 103", "Sector 104", "Sector 105", "Sector 106", "Sector 107", "Sector 108", "Sector 109", "Sector 110", "Sector 111", "Sector 112", "Sector 113", "Sector 114", "Sector 115", "Sector 116", "Sector 117", "Sector 118", "Sector 119", "Sector 120", "Sector 121", "Sector 122", "Sector 123", "Sector 124", "Sector 125", "Sector 126", "Sector 127"],
  "Moradabad": ["Civil Lines", "Budh Bazar", "Majhola", "Kanth Road", "Ram Ganga Vihar", "Pakbara", "Katghar", "Mughalpura", "Nawabpura"],
  "Mumbai": ["Airoli", "Amboli", "Andheri", "Antop Hill", "Bandra", "Bhandup", "Bhayandar", "Borivali", "Byculla", "CBD Belapur", "Chembur", "Dadar", "Dahisar East", "Dahisar West", "Dahisar", "Dombivli East", "Dongri", "Ganesh Galli", "Garodia Nagar", "Ghatkopar", "Girgaon", "Goregaon", "Govandi", "Grant Road", "IC Colony", "J.B. Nagar", "Jogeshwari", "Kalina", "Kandivali", "Kanjurmarg", "Khar", "Kharghar", "Kurla", "Lower Parel", "Mahalaxmi", "Mahim", "Malad", "Marine Lines", "Matunga", "Mazagaon", "Mira Road", "Mulund", "Mumbra", "Nala Sopara", "Nariman Point", "Navi Mumbai", "Nerul", "Panvel", "Powai", "Sakinaka", "Sanpada", "Santacruz East", "Santacruz West", "Santacruz", "South Mumbai", "Thane", "Tilak Nagar", "Trombay", "Ulwe", "Vikhroli", "Vile Parle East", "Virar", "Wadala"],
  "Mysuru": ["Vijayanagar", "Hebbal", "Gokulam", "Jayalakshmipuram", "Saraswathipuram", "Kuvempunagar", "Chamundipuram", "Siddhartha Layout", "Hootagalli", "Bannimantap", "Alanahalli", "Yadavagiri", "Lakshmipuram", "Vontikoppal", "Bogadi", "Srirampura"],
  "Nadiad": ["College Road", "Pij Road", "Nana Kumbhnath Road", "Mission Road", "Mahagujarat Hospital Area", "Santram Road", "Vaniyavad"],
  "Nagpur": ["Dharampeth", "Ramdaspeth", "Laxmi Nagar", "Shankar Nagar", "Sadar", "Civil Lines", "Sitabuldi", "Mahal", "Itwari", "Mankapur", "Jaripatka", "Kamptee Road", "Manish Nagar", "Narendra Nagar", "Nandanvan", "Khamla", "Trimurti Nagar", "Pratap Nagar", "Bajaj Nagar", "Wardhaman Nagar", "Koradi Road", "Hingna", "MIHAN", "Umred Road", "Medical Square"],
  "Nanded": ["Vishnupuri", "CIDCO", "Taroda Naka", "Degloor Naka", "Shivaji Nagar", "Vazirabad", "Anand Nagar", "Itwara"],
  "Narsipatnam": ["Main Road Area", "Chintapalli Road", "Kotha Road Area", "RTC Complex Area", "Gandhi Chowk"],
  "Nashik": ["College Road", "Gangapur Road", "Indira Nagar", "Pathardi Phata", "Canada Corner", "Panchavati", "Dwarka", "Mhasrul", "Satpur", "Govind Nagar"],
  "Nizamabad": ["Vinayak Nagar", "Pragathi Nagar", "Khaleelwadi", "Yellammagutta", "Mubarak Nagar", "Armoor Road", "Giriraj Nagar"],
  "Noida": ["Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6", "Sector 7", "Sector 8", "Sector 9", "Sector 10", "Sector 11", "Sector 12", "Sector 13", "Sector 14", "Sector 15", "Sector 16", "Sector 17", "Sector 18", "Sector 19", "Sector 20", "Sector 21", "Sector 22", "Sector 23", "Sector 24", "Sector 25", "Sector 26", "Sector 27", "Sector 28", "Sector 29", "Sector 30", "Sector 31", "Sector 32", "Sector 33", "Sector 34", "Sector 35", "Sector 36", "Sector 37", "Sector 38", "Sector 39", "Sector 40", "Sector 41", "Sector 42", "Sector 43", "Sector 44", "Sector 45", "Sector 46", "Sector 47", "Sector 48", "Sector 49", "Sector 50", "Sector 51", "Sector 52", "Sector 53", "Sector 54", "Sector 55", "Sector 56", "Sector 57", "Sector 58", "Sector 59", "Sector 60", "Sector 61", "Sector 62", "Sector 63", "Sector 64", "Sector 65", "Sector 66", "Sector 67", "Sector 68", "Sector 69", "Sector 70", "Sector 71", "Sector 72", "Sector 73", "Sector 74", "Sector 75", "Sector 76", "Sector 77", "Sector 78", "Sector 79", "Sector 80", "Sector 81", "Sector 82", "Sector 83", "Sector 84", "Sector 85", "Sector 86", "Sector 87", "Sector 88", "Sector 89", "Sector 90", "Sector 91", "Sector 92", "Sector 93", "Sector 94", "Sector 95", "Sector 102", "Sector 103", "Sector 104", "Sector 105", "Sector 106", "Sector 107", "Sector 108", "Sector 109", "Sector 110", "Sector 111", "Sector 112", "Sector 113", "Sector 114", "Sector 115", "Sector 116", "Sector 117", "Sector 118", "Sector 119", "Sector 120", "Sector 121", "Sector 122", "Sector 123", "Sector 124", "Sector 125", "Sector 126", "Sector 127", "Sector 128", "Sector 129", "Sector 130", "Sector 131", "Sector 132", "Sector 133", "Sector 134", "Sector 135", "Sector 136", "Sector 137", "Sector 138", "Sector 139", "Sector 140", "Sector 140A", "Sector 141", "Sector 142", "Sector 143", "Sector 143A", "Sector 143B", "Sector 144", "Sector 145", "Sector 146", "Sector 147", "Sector 148", "Sector 149", "Sector 150", "Sector 151", "Sector 152", "Sector 153", "Sector 154", "Sector 155", "Sector 156", "Sector 157", "Sector 158", "Sector 159", "Sector 160", "Sector 161", "Sector 162", "Sector 163", "Sector 164", "Sector 165", "Sector 166", "Sector 167", "Sector 168"],
  "Panchkula": ["Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6", "Sector 7", "Sector 8", "Sector 9", "Sector 10", "Sector 11", "Sector 12", "Sector 12A", "Sector 13", "Sector 14", "Sector 15", "Sector 16", "Sector 17", "Sector 18", "Sector 19", "Sector 20", "Sector 21", "Sector 22", "Sector 23", "Sector 24", "Sector 25", "Sector 26", "Sector 27", "Sector 28"],
  "Panipat": ["Model Town", "HUDA Sector 11", "HUDA Sector 12", "Tehsil Camp", "Assandh Road", "Sanoli Road", "GT Road Area"],
  "Pathankot": ["Dalhousie Road", "Improvement Trust Area", "Model Town", "Lamini", "Mamoon Cantt", "Malikpur"],
  "Patiala": ["Model Town", "Urban Estate Phase 1", "Urban Estate Phase 2", "Leela Bhawan", "Tripuri", "Rajpura Road", "Bhadson Road"],
  "Patna": ["AIIMS Patna Road", "Anandpuri", "Anisabad", "Ashiana Nagar", "Ashok Rajpath", "Bailey Road", "Bihta", "Boring Road", "Bypass Chowk", "Dak Bungalow Road", "Danapur", "Digha", "Exhibition Road", "Fraser Road", "Gola Road", "Gulzarbagh", "Jagdeo Path", "Kankarbagh", "Khagaul Road", "Kidwaipuri", "Kurji", "Mithapur", "Nehru Nagar", "New Patliputra Colony", "Pahleja Ghat", "Patliputra Colony", "Patna City", "Patna Sahib", "Phulwari Sharif", "Raja Bazar", "Raja Bazar", "Rajendra Nagar", "Rajendranagar Terminal", "Rukanpura", "Saguna More", "Sheikhpura", "Shivpuri"],
  "Pondicherry": ["White Town", "Heritage Town", "Muthialpet", "Lawspet", "Reddiarpalayam", "Rainbow Nagar", "Ariyankuppam", "Mudaliarpet", "Kalapet", "Bahour"],
  "Allahabad": ["Civil Lines", "Katra", "George Town", "Naini", "Jhunsi", "Allahpur", "Tagore Town", "Mumfordganj", "Rajapur", "Daraganj"],
  "Pune": ["Agarkar Nagar", "Akurdi", "Alandi", "Ambegaon Budruk", "Aundh", "Balewadi", "Baner", "Bavdhan", "Bhau Patil Road", "Bhosari", "Bhugaon", "Bhusari Colony", "Bibwewadi", "Bopodi", "Camp", "Chakan MIDC", "Chakan", "Chinchwad", "Chinchwadgaon", "Dange Chowk", "Dapodi", "Deccan Gymkhana", "Dhankawadi", "Dhanori", "Dhayari", "Dighi", "Erandwane", "Fatima Nagar", "Fursungi", "Gahunje", "Ganesh Peth", "Ganeshkhind", "Gangadham", "Ghorpadi", "Ghorpuri", "Gokhale Nagar", "Gultekdi", "Guru Nanak Nagar", "Hadapsar", "Handewadi Road", "Hinjawadi", "Indapur", "Indrayani Nagar", "JM Road", "Jagtap Dairy", "Jai Bhavani Nagar", "Jambhulwadi", "Janardannagar", "Kalyani Nagar", "Kamshet", "Karve Nagar", "Katraj", "Kedari Nagar", "Keshav Nagar", "Khadakwasla", "Khadki", "Khandala", "Kharadi", "Khondhwa", "Kothrud(Pune)", "Kothrud", "Lohegaon", "Lonavala", "Lonikand", "Lulla Nagar", "Magarpatta City", "Mahalunge", "Maharshi Nagar", "Mahatma Phule Peth", "Manjari Budruk", "Manjari", "Market Yard", "Marunji", "Mohammadwadi", "Moshi", "Mundhwa", "NIBM Road", "Nana Peth", "Nanded City", "Nanded", "Naneghat", "Narhe", "Navi Peth", "Navsahyadri", "Nehru Nagar", "Nigdi", "Old Mumbai Pune Highway", "Padmavati", "Pashan Sus Road", "Pashan", "Pimple Gurav", "Pimple Nilakh", "Pimple Saudagar", "Pimpri Chinchwad", "Pimpri", "Pirangut", "Pradhikaran", "Pulachi Wadi", "Rasta Peth", "Ravet", "Sadashiv Peth", "Sahakar Nagar", "Salisbury Park", "Sangamwadi", "Saswad", "Satara Road", "Shivajinagar", "Sinhagad Road", "Sus", "Sutarwadi", "Swargate", "Talawade", "Talegaon Dabhade", "Tathawade", "Thergaon", "Tingre Nagar", "Undri", "Uruli Devachi", "Vadgaon Budruk", "Vadgaon Sheri", "Viman Nagar", "Vishrantwadi", "Wadgaon Sheri", "Wagholi", "Wakad", "Wanwadi", "Warje", "Yerawada"],
  "Raipur": ["Shankar Nagar", "Pandri", "Telibandha", "Mowa", "Devendra Nagar", "Samta Colony", "Avanti Vihar", "Tatibandh", "VIP Road Area", "Kota"],
  "Rajkot": ["Kalawad Road", "University Road", "Race Course Road", "Raiya Road", "150 Feet Ring Road", "Nana Mava Road", "Madhapar", "Kotharia", "Mavdi", "Gondal Road"],
  "Ranchi": ["Morabadi", "Lalpur", "Harmu", "Doranda", "Ashok Nagar", "Bariatu", "Kanke Road", "Booty More", "Namkum", "Upper Bazar"],
  "Rourkela": ["Civil Township", "Chhend Colony", "Udit Nagar", "Basanti Colony", "Koelnagar", "Panposh", "Fertilizer Township", "Bondamunda", "Sector 2", "Sector 5"],
  "Salem": ["Fairlands", "Alagapuram", "Hasthampatti", "Ammapet", "Suramangalam", "Gugai", "Shevapet", "Swarnapuri", "Meyyanur"],
  "Siliguri": ["Sevoke Road", "Pradhan Nagar", "Hakimpara", "Ashrampara", "Champasari", "Matigara", "Dagapur", "Salugara", "Bidhan Market Area"],
  "Sri Ganganagar": ["Jawahar Nagar", "Shastri Nagar", "Civil Lines", "Riddhi Siddhi Enclave", "Padampur Road", "Suratgarh Road", "Kesrisinghpur Road"],
  "Srinagar": ["Lal Chowk", "Rajbagh", "Jawahar Nagar", "Bemina", "Batamaloo", "Hazratbal", "Rainawari", "Nishat", "Shalimar"],
  "Surat": ["Adajan", "Vesu", "City Light", "Pal", "Palanpur", "Katargam", "Varachha", "Mota Varachha", "Nana Varachha", "Udhna", "Piplod", "Althan", "Dumas Road", "Bhatar", "Nanpura", "Majura Gate", "Athwa", "Limbayat", "Sachin", "Hazira Road", "Rander", "Pandesara", "Ghod Dod Road"],
  "Thane": ["Ghodbunder Road", "Majiwada", "Vartak Nagar", "Vasant Vihar", "Lok Puram", "Kolshet", "Kalwa", "Mumbra", "Manpada", "Kasarvadavali", "Owale", "Balkum", "Wagle Estate", "Kopri", "Naupada", "Panchpakhadi", "Hiranandani Estate", "Yeoor Hills"],
  "Thrissur": ["Punkunnam", "Ayyanthole", "Ollur", "East Fort", "West Fort", "Vadakke Stand", "Kuriachira", "Poothole", "Mannuthy", "Kuttur"],
  "Trivandrum": ["Akkulam", "Alamcode", "Ambalamukku", "Ambalathara", "Anad", "Anayara", "Andoorkonam", "Arappuramukku", "Aruvikkara", "Aryanad", "Athiyannoor", "Attakulangara", "Attingal", "Ayiroopara", "Azhoor", "Balaramapuram", "Chacka", "Chalai", "Chanthavila", "Chempazhanthy", "Chenkal", "Chirayinkeezhu", "EastFort", "Gandhipuram", "Idapazhanji", "Jagathy", "JawaharNagar", "Kadakampally", "Kadinamkulam", "Kaithamukku", "Kalady", "Kallampally", "Kallara", "Kallayam", "Kallikad", "Kalliyoor", "Kaniyapuram", "Kanjiramkulam", "Karakulam", "Karamana", "Karipooru", "Karode", "Karumkulam", "Kattakada", "Kazhakkoottam", "Keezharoor", "Keezhthonakkal", "Kesavadasapuram", "Killipalam", "Kochulloor", "Kochuveli", "Kollayil", "Kottukal", "Kovalam", "Kowdiar", "Kudappanakunnu", "Kulasekharam", "Kulathoor", "Kulathummal", "Kundamankadavu", "Kunnathukal", "Kunnukuzhi", "Kuruppuzha", "Kuzhivila", "Malayinkeezhu", "Manacaud", "Manikkal", "Mannoorkara", "Manvila", "Marappalam", "Maruthumkuzhi", "Melthonnakkal", "Menamkulam", "Mudavanmugal", "Mukkolakkal", "Muttada", "Muttathara", "Nalanchira", "Nandavanam", "Navaikulam", "Nedumangadu", "Nemom", "Nettayam", "Neyyattinkara", "Njandoorkonam", "Oottukuzhy", "PMG", "Palayam", "Palkulangara", "Pallichal", "Pallickal", "Palode", "Panavoor", "Pangappara", "Pangode", "Pappanamcode", "Parasala", "Parasuvakkal", "Paruthippara", "Pattom", "Perinjamala", "Peroorkada", "Perumkadavila", "Perumkulam", "Perumpazhuthoor", "Pettah", "Poojapura", "Poovar", "Pothencode", "Powdikonam", "Pulayanarkotta", "Pulimoodu", "Pullampara", "Sasthamangalam", "Shangumukham", "SreeVaraham", "Sreekaryam", "Thekkada", "Thennoor", "Thirumala", "Thirupuram", "Thiruvallam", "Thiruvananthapuram", "Tholikkode", "Thonnakkal", "Thycaud", "Uliyazhathura", "Ulloor", "Uzhamalakkal", "Vakkom", "Valiyavila", "Vamanapuram", "Vanchiyoor", "Varkala", "Vattapara", "Vattiyoorkavu", "Vazhayila", "Vazhuthacaud", "Veeranakavu", "Veiloor", "Vellanad", "Vellayambalam", "Vellayani", "Vembayam", "Venganoor", "Vettamukku", "Vilappil", "Vithura", "Vizhinjam"],
  "Tumakuru": ["Ashok Nagar", "SS Puram", "Maralur", "Siddaganga Layout", "Kuvempunagar", "Ward 18 Area", "Batawadi", "Kyathsandra", "Gubbi Road"]
};

export const TIME_PERIODS_DATA: Record<string, string[]> = {
    'Morning': [
        '06:00 AM', '06:30 AM', '07:00 AM', '07:30 AM', '08:00 AM',
        '08:30 AM', '09:00 AM', '09:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM'
    ],
    'Afternoon': [
        '12:00 PM', '12:30 PM', '01:00 PM', '01:30 PM', '02:00 PM',
        '02:30 PM', '03:00 PM', '03:30 PM'
    ],
    'Evening': [
        '04:00 PM', '04:30 PM', '05:00 PM', '05:30 PM', '06:00 PM',
        '06:30 PM', '07:00 PM', '07:30 PM', '08:00 PM', '08:30 PM', '09:00 PM'
    ]
};

export const DAY_GROUPS_DATA = {
    'Weekdays': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    'Weekend': ['Saturday', 'Sunday']
};
